export const VISIT_SCAN_SUCCESS_MODAL_AUTO_CLOSE_SECONDS = 3;

export const VISIT_SCAN_ERROR_MODAL_AUTO_CLOSE_SECONDS = 3;

export const PUBLIC_SCANNER_COOLDOWN_MS = 5000;

export const PUBLIC_SCANNER_BLOCKED_INPUT_TIMEOUT_MS = 120;

export const ADMIN_ROUTE_PRELOADER_MINIMUM_MS = 2;
